In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
#Dataframes
Pre_2018 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','Pre2018'))
S2_2018 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2018 Fall'))
S1_2019 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2019 S1_someduplicates w 2019S2'))
S2_2019 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2019 S2'))
S1_2020 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2022 S1'))
S1_2021 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2021(only NSOE courses data)'))
S1_2022 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2022 S1'))
S2_2022 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2022 S2'))
S1_2023 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2023 S1'))
S2_2023 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2023 S2'))

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## COLUMN STANDARDIZING

notes:

2019 S1 has both S1 and S2 data

what to do with rows like: R_DP3nmM33daUAcTv in S1_2023


## TODO:
The NAN's in Herp_obs of S2_2018 arent changing to No's

In [4]:
# Convert column names to sets
#columns_df1 = {'Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team', 'Email', 'Observer', 'Other_Observers', 'Temperature', 'Sky_condition', 'Complete_transect', 'Complete_reason', 'Herp_obs', 'Ant_obs', 'Flag', 'Flag_details', 'SP', 'SP_Cover_ID', 'SP_Total', 'SP_Photo', 'Dead_animal', 'Dead_detail', 'Other_animal', 'Other_detail', 'Upload_photo', 'Upload_sheet', 'Comments', 'Administrative_comments','Extra photo 1', 'Extra photo 1', 'Extra photo 1', 'Extra photo 1', 'Extra photo 2', 'Extra photo 2', 'Extra photo 2', 'Extra photo 2',}
columns_df1 = set(S2_2023)
columns_df2 = set(Pre_2018)
#columns_df2 = {"Date", "Time", "Transect_ID", "Temperature", "Weather", "Organization", "Community_team", "Email", "Observer", "Complete_transect", "Check_reason", "Herp_obs", "Ant_obs", "Flag", "Flag_details", "SP_Repeat", "SP", "SP_Cover", "SP_Count", "SP_Photo", "Dead_animal", "Dead_detail", "Other_animal", "Other_detail", "Upload_photo", "Upload_sheet", "Comments"}

# Find columns unique to df2
unique_to_df2 = columns_df2 - columns_df1

unique_to_df1 = columns_df1 - columns_df2

print(unique_to_df2)

{'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10', 'Observer Info - Other Observers', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2', 'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Id', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.13', 'Are you a Citizen Scientist or are you participating in a Duke class?', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9', 'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10', 'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.', 'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Type', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).13', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4', 'Observer Info - Recorder (you)', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2', 'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name', 'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes and transect conditions can be submitted at the end).', 'Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12', 'Air Temperature (Â°F)', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7', 'Upload a ZIP file of all of your photos: - Id', 'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Size', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8', 'Which transect did you survey?', 'What was the weather like?', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.13', 'Did you find any herps at this transect?', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12', 'Upload a ZIP file of all of your photos: - Name', 'Upload a ZIP file of all of your photos: - Type', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11', 'Upload a ZIP file of all of your photos: - Size', 'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6'}

### Pre 2018

In [5]:
new_column_name = 'x'
insert_position = Pre_2018.columns.get_loc('Species/Occurrence 10') + 1
Pre_2018.insert(insert_position, new_column_name, np.nan)
new_column_name = 'y'
insert_position = Pre_2018.columns.get_loc('Species/Occurrence 10') + 2
Pre_2018.insert(insert_position, new_column_name, np.nan)
new_column_name = 'z'
insert_position = Pre_2018.columns.get_loc('Species/Occurrence 10') + 3
Pre_2018.insert(insert_position, new_column_name, np.nan)
new_column_name = 'Administrative_comments'
insert_position = Pre_2018.columns.get_loc('Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.') + 1
Pre_2018.insert(insert_position, new_column_name, np.nan)

In [6]:
Pre_2018 = Pre_2018.drop(Pre_2018.index[[0, 1]])
Pre_2018.rename(columns={'Response ID' : 'Response_ID',\
                                  'Which transect did you survey?' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)' : 'Start_time',\
                                  'Are you a Citizen Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Info - Recorder (you)" : 'Observer',\
                                  "Observer Info - Other Observers" : 'Other_Observers',\
                                  'Air Temperature (Â°F)' : 'Temperature',\
                                  'What was the weather like?' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes and transect conditions can be submitted at the end).' : 'Flag_details',\
                                  'Upload a ZIP file of all of your photos: - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name' : 'Upload_sheet',\
                                  'Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.' : 'Comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_5_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_5_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_6_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_6_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_7_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_7_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_8_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_8_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_9_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_9_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 10')+1]: 'SP_10_Cover_ID', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 10')+2]: 'SP_10_Total', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 10')+3]: 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  Pre_2018.columns[Pre_2018.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_13_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_13_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_14_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_14_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.13': 'SP_15_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.13': 'SP_15_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).13': 'SP_15_Photo'}, inplace=True)

### 2018 FALL

In [7]:
S2_2018

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Which transect did you survey?,Survey Date (mm/dd/yyyy),"Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)",Are you a Citizen Scientist or are you participating in a Duke class?,What team was scheduled for this transect?,Observer Info - Recorder (you),Observer Info - Other Observers,Email Address,What was the weather like?,Air Temperature (Â°F),Did you check all 15 pieces of cover along this transect?,"If not, which pieces did you not check and why?",Did you find any herps at this transect?,"Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may ""flag"" your data for our team to review.","If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture) you are referring.\n\n(General notes and transect conditions can be submitted at the end).",Species/Occurrence 1,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n)",Species/Occurrence 2,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1",Species/Occurrence 3,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2",Species/Occurrence 4,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3",Species/Occurrence 5,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4",Record more Species/Occurrences?,Species/Occurrence 6,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5",Species/Occurrence 7,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6",Species/Occurrence 8,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7",Species/Occurrence 9,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8",Species/Occurrence 10,Record more Species/Occurrences?.1,Species/Occurrence 11,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9",Species/Occurrence 12,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10",Species/Occurrence 13,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11",Species/Occurrence 14,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12",Species/Occurrence 15,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.13","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.13","Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).13",Upload a ZIP file of all of your photos: - Id,Upload a ZIP file of all of your photos: - Name,Upload a ZIP file of all of your photos: - Size,Upload a ZIP file of all of your photos: - Type,"Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.",Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Id,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Size,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Type,Extra photo 1,Extra photo 1.1,Extra photo 1.2,Extra photo 1.3,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107
0,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1.2,Q2.2,Q2.3,Q2.4,Q2.5,Q2.6_1,Q2.6_2,Q2.7,Q2.8,Q2.9,Q2.10,Q2.11,Q2.12,Q2.13,Q2.14,Q3.2,Q3.3_1_1,Q3.3_1_2,Q3.3_1_4,Q3.4,Q3.5_1_1,Q3.5_1_2,Q3.5_1_4,Q3.6,Q3.7_1_1,Q3.7_1_2,Q3.7_1_4,Q3.8,Q3.9_1_1,Q3.9_1_2,Q3.9_1_4,Q3.10,Q3.11_1_1,Q3.11_1_2,Q3.11_1_4,Q3.12,Q3.13,Q3.14_1_1,Q3.14_1_2,Q3.14_1_4,Q3.15,Q3.16_1_1,Q3.16_1_2,Q3.16_1_4,Q3.17,Q3.18_1_1,Q3.18_1_2,Q3.18_1_4,Q3.19,Q3.20_1_1,Q3.20_1_2,Q3.20_1_4,Q3.21,Q3.22,Q3.23,Q3.24_1_1,Q3.24_1_2,Q3.24_1_4,Q3.25,Q3.26_1_1,Q3.26_1_2,Q3.26_1_4,Q3.27,Q3.28_1_1,Q3.28_1_2,Q3.28_1_4,Q3.29,Q3.30_1_1,Q3.30_1_2,Q3.30_1_4,Q3.31,Q3.32_1_1,Q3.32_1_2,Q3.32_1_4,Q4.3_Id,Q4.3_Name,Q4.3_Size,Q4.3_Type,Q4.4,Q4.5_Id,Q4.5_Name,Q4.5_Size,Q4.5_Type,Photo Upload: - Id,Photo Upload: - Name,Photo Upload: - Size,Photo Upload: - Type,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-08-28 14:30:56,2018-08-28 14:35:15,IP Address,107.15.248.74,100,259,True,2018-08-28 14:35:20,R_BDKkrLu1xspw7eh,NaN,NaN,NaN,NaN,36.037796,-78.985802,anonymous,EN,Gate C-1 (DU_4_GC_C61),2018-08-28 00:00:00,3:00pm - 4:00pm,Citizen Scientist,NaN,"Cagle, Nicolette","Cagle, Grant",NaN,Mostly Sunny,91,NaN,NaN,Yes,NaN,NaN,Skink (Unidentified),W-6,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_2sdJmSyeNfttOsk,28Aug2018 Durham Duke Forest skink transect DU...,2010617,image/jpeg,NaN,F_1dyLNcB5rR0a6za,IMG_20180828_0002.pdf,617532,application/pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-08-30 13:39:03,2018-08-30 13:55:26,IP Address,71.69.177.241,100,982,True,2018-08-30 13:55:27,R_3rSSt8H4V0qrxpg,NaN,NaN,NaN,NaN,36.0755,-79.074097,anonymous,EN,Gate 8 (DU_5_G8_C62),2018-08-29 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Richard DAngiolillo,Bill Boyarsky,NaN,Mostly Sunny,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We were wondering if we might find more herps ...,F_2EfNBO49J64T7bi,DU_5_G8_C62 Aug 29 2018.pdf,69436,application/pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-09-01 08:35:03,2018-09-01 08:37:28,IP Address,75.40.153.41,100,145,True,2018-09-01 08:37:31,R_voU1RnHm9aPnqz7,NaN,NaN,NaN,NaN,35.949997,-78.961601,anonymous,EN,Gate 48 (DU_11_G48_C82),2018-09-01 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Robin Franklin,Cathy Brennan,NaN,Sunny,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We saw an American Toad on our walk out!,F_2D6LnJrMqUw4S5r,TransecT-11 090118.pdf,3053261,application/pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2018-09-01 17:54:29,2018-09-01 18:22:38,IP Address,174.109.75.84,100,1688,True,2018-09-01 18:22:41,R_dbTWfk6WyKLsaCR,NaN,NaN,NaN,NaN,36.037796,-78.985802,anonymous,EN,Gate 4 (DU_1_G4_C52),2018-09-01 00:00:00,10:00am - 11:00am,Citizen Scientist,NaN,Barb Dietsch,Richard McFall,NaN,Mostly Sunny,84,NaN,NaN,Yes,NaN,NaN,Smooth Earth Snake (Virginia valeriae),W-5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_2pWwQEoHXbWWCi6,DU_1_G4_Wood5_1Sept2018.jpg,305093,image/jpeg,Stations W1 and W6 are so rotten that the turn...,F_2wuwkL2RXkSZ1Ah,DU_1_G4_SheeT-1Sept2018.jpg,206826,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2018-09-02 07:31:47,2018-09-02 07:39:34,IP Address,45.37.182.86,100,467,True,2018-09-02 07:39:36,R_3nrrdY9sKDV8361,NaN,NaN,NaN,NaN,35.889603,-78.9244,anonymous,EN,Gate 48 (DU_12_G48_C76),2018-09-01 00:00:00,2:00pm - 3:00pm,Citizen Scientist,NaN,Amber Meade,Jason Nichols,NaN,Mostly Sunny,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"When looking for W8, we found a very rotted bo...",F_2xRbqkhTEbJz2Nd,Herp sheet 9-1-18.jpg,35288,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2018-09-04 11:50:49,2018-09-04 11:56:33,IP Address,99.29.112.111,100,343,True,2018-09-04 11:56:35,R_BKUjcp8vm9aRoxH,NaN,NaN,NaN,NaN,35.949997,-78.961601,anonymous,EN,Gate 22 (DU_13_G22_C85),2018-09-01 00:00:00,11:00am - 12:00pm,Citizen Scientist,NaN,Jason Elliott,Joshua Smith,NaN,Sunny,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"The W10 board was falling apart some, so maybe...",F_pgZOxRtfUEHvI65,IMG_0941.jpg,749636,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2018-09-04 14:50:24,2018-09-04 14:59:17,IP Address,71.210.12.20,100,533,True,2018-09-04 14:59:19,R_3RxcmWiPAnV5xmB,NaN,NaN,NaN,NaN,36.348206,-78.646301,anonymous,EN,Gate 8 (DU_5_G8_C62),2018-09-04 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Boyarsky,DAngiolillo,NaN,Sunny,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"T1 had a roughly 8"" intact snake shed, left al...",F_Z8iK7lc9gr9DnDr,DU5G8C62-20180904-sheet.pdf,62500,application/pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2018-09-08 08:41:52,2018-09-08 08:45:05,IP Address,75.40.153.41,100,192,True,2018-09-08 08:45:07,R_3oZ1UVOhBXtAxkt,NaN,NaN,NaN,NaN,35.949997,-78.961601,anonymous,EN,Gate 48 (DU_12_G48_C76),2018-09-08 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Robin Franklin,Cathy Brennan,NaN,Mostly Sunny,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We saw a cool metallic purple beetle under one...,F_2b1q7fv34lGC5vf,TransecT-12 090818.pdf,163179,application/pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2018-09-08 15:45:21,2018-09-08 16:00:37,IP Address,104.129.204.134,100,915,True,2018-09-08 16:00:40,R_3fqkKAa5IDLrqjq,NaN,NaN,NaN,NaN,37.789795,-122.245697,anonymous,EN,Gate 22 (DU_13_G22_C85),2018-09-08 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Amber Meade,Jason Nichols,NaN,Sunny,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It would be good to update the description of ...,F_2ZPPMhl8l5l9ET8,IMG_0422[1].JPG,2984670,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2018-09-08 16:00:43,2018-09-08 16:03:22,IP Address,104.129.204.134,100,159,True,2018-09-08 16:03:26,R_1o27z1Lb3NcF52M,NaN,NaN,NaN,NaN,37.789795,-122.245697,anonymous,EN,Gate 48 (DU_11_G48_C82),2018-09-08 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Amber Meade,Jason Nichols,NaN,Mostly Sunny,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_1rHOkV0EvDiWcM5,IMG_0423[1].JPG,2957547,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2018-09-13 14:20:35,2018-09-13 14:24:12,IP Address,174.109.65.77,100,216,True,2018-09-13 14:24:16,R_3m7t5svM9wRDmHB,NaN,NaN,NaN,NaN,36.037796,-78.985802,anonymous,EN,Gate 4 (DU_1_G4_C52),2018-09-08 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,"Sean, Farmer","Mack, McFall",NaN,Sunny,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_AMZyTODqaiS28E1,20180913_160900.jpg,4219752,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2018-09-16 16:06:47,2018-09-16 16:10:16,IP Address,98.26.50.184,100,209,True,2018-09-16 16:10:18,R_3k6WaBO68G3OPmy,NaN,NaN,NaN,NaN,36.035507,-78.839104,anonymous,EN,Gate 8 (DU_5_G8_C62),2018-09-16 00:00:00,4:00pm - 5:00pm,Citizen Scientist,NaN,Cat Angst,Jason Driver,NaN,Rainy,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We drove past the gate several times. The flag...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2018-09-18 15:02:18,2018-09-18 15:16:34,IP Address,152.16.191.122,100,856,True,2018-09-18 15:16:49,R_usO9msqZVX9ltjb,NaN,NaN,NaN,NaN,35.946594,-78.797699,anonymous,EN,Gate C-1 (DU_4_GC_C61),2018-09-08 00:00:00,10:00am - 11:00am,Citizen Scientist,NaN,Barb Dietsch,Barbara Beaman,NaN,Sunny,72,NaN,NaN,Yes,NaN,NaN,Ground Skink (Scincella lateralis),T-1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_3nH6dXi2BdW6xKQ,"Scincella lateralis -Sept 8, 2018 under T1.JPG",2099616,image/jpeg,I think that the tin coverboards are too large...,F_1nV084ReOL7DyZ0,"Data Sheet - Sept 8, 2018.jpg",6760860,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
new_column_name = 'x'
insert_position = S2_2018.columns.get_loc('Species/Occurrence 10') + 1
S2_2018.insert(insert_position, new_column_name, np.nan)
new_column_name = 'y'
insert_position = S2_2018.columns.get_loc('Species/Occurrence 10') + 2
S2_2018.insert(insert_position, new_column_name, np.nan)
new_column_name = 'z'
insert_position = S2_2018.columns.get_loc('Species/Occurrence 10') + 3
S2_2018.insert(insert_position, new_column_name, np.nan)
new_column_name = 'Administrative_comments'
insert_position = S2_2018.columns.get_loc('Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.') + 1
S2_2018.insert(insert_position, new_column_name, np.nan)

In [9]:
remove_position = S2_2018.columns.get_loc('Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Type')+1
S2_2018.drop(S2_2018.columns[[remove_position + 1, remove_position + 2, remove_position + 3, remove_position + 5,remove_position + 6,remove_position + 7]], axis=1, inplace=True)

In [10]:
S2_2018 = S2_2018.drop(S2_2018.index[[0, 1]])
S2_2018.rename(columns={'Response ID' : 'Response_ID',\
                                  'Which transect did you survey?' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)' : 'Start_time',\
                                  'Are you a Citizen Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Info - Recorder (you)" : 'Observer',\
                                  "Observer Info - Other Observers" : 'Other_Observers',\
                                  'Air Temperature (Â°F)' : 'Temperature',\
                                  'What was the weather like?' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes and transect conditions can be submitted at the end).' : 'Flag_details',\
                                  'Upload a ZIP file of all of your photos: - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name' : 'Upload_sheet',\
                                  'Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.' : 'Comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_5_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_5_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_6_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_6_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_7_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_7_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_8_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_8_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_9_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_9_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 10')+1]: 'SP_10_Cover_ID', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 10')+2]: 'SP_10_Total', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 10')+3]: 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S2_2018.columns[S2_2018.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_13_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_13_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_14_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_14_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.13': 'SP_15_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.13': 'SP_15_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).13': 'SP_15_Photo',\
                                  'Unnamed: 104' : 'Extra photo 2'}, inplace=True)

In [11]:
for index, row in S2_2018.iterrows():
        if row['Herp_obs'] == np.nan:
            S2_2018.at[index, 'Herp_obs'] = 'No'

In [12]:
S2_2018.head()

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response_ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Transect_ID,Date,Start_time,Affiliation,Community_team,Observer,Other_Observers,Email,Sky_condition,Temperature,Complete_transect,Complete_reason,Herp_obs,Flag,Flag_details,SP_1,SP_1_Cover_ID,SP_1_Total,SP_1_Photo,SP_2,SP_2_Cover_ID,SP_2_Total,SP_2_Photo,SP_3,SP_3_Cover_ID,SP_3_Total,SP_3_Photo,SP_4,SP_4_Cover_ID,SP_4_Total,SP_4_Photo,SP_5,SP_5_Cover_ID,SP_5_Total,SP_5_Photo,Record more Species/Occurrences?,SP_6,SP_6_Cover_ID,SP_6_Total,SP_6_Photo,SP_7,SP_7_Cover_ID,SP_7_Total,SP_7_Photo,SP_8,SP_8_Cover_ID,SP_8_Total,SP_8_Photo,SP_9,SP_9_Cover_ID,SP_9_Total,SP_9_Photo,SP_10,SP_10_Cover_ID,SP_10_Total,SP_10_Photo,Record more Species/Occurrences?.1,SP_11,SP_11_Cover_ID,SP_11_Total,SP_11_Photo,SP_12,SP_12_Cover_ID,SP_12_Total,SP_12_Photo,SP_13,SP_13_Cover_ID,SP_13_Total,SP_13_Photo,SP_14,SP_14_Cover_ID,SP_14_Total,SP_14_Photo,SP_15,SP_15_Cover_ID,SP_15_Total,SP_15_Photo,Upload a ZIP file of all of your photos: - Id,Upload_photo,Upload a ZIP file of all of your photos: - Size,Upload a ZIP file of all of your photos: - Type,Comments,Administrative_comments,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Id,Upload_sheet,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Size,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Type,Extra photo 1,Extra photo 2
2,2018-08-28 14:30:56,2018-08-28 14:35:15,IP Address,107.15.248.74,100,259,True,2018-08-28 14:35:20,R_BDKkrLu1xspw7eh,NaN,NaN,NaN,NaN,36.037796,-78.985802,anonymous,EN,Gate C-1 (DU_4_GC_C61),2018-08-28 00:00:00,3:00pm - 4:00pm,Citizen Scientist,NaN,"Cagle, Nicolette","Cagle, Grant",NaN,Mostly Sunny,91,NaN,NaN,Yes,NaN,NaN,Skink (Unidentified),W-6,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_2sdJmSyeNfttOsk,28Aug2018 Durham Duke Forest skink transect DU...,2010617,image/jpeg,NaN,NaN,F_1dyLNcB5rR0a6za,IMG_20180828_0002.pdf,617532,application/pdf,NaN,NaN
3,2018-08-30 13:39:03,2018-08-30 13:55:26,IP Address,71.69.177.241,100,982,True,2018-08-30 13:55:27,R_3rSSt8H4V0qrxpg,NaN,NaN,NaN,NaN,36.0755,-79.074097,anonymous,EN,Gate 8 (DU_5_G8_C62),2018-08-29 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Richard DAngiolillo,Bill Boyarsky,NaN,Mostly Sunny,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We were wondering if we might find more herps ...,NaN,F_2EfNBO49J64T7bi,DU_5_G8_C62 Aug 29 2018.pdf,69436,application/pdf,NaN,NaN
4,2018-09-01 08:35:03,2018-09-01 08:37:28,IP Address,75.40.153.41,100,145,True,2018-09-01 08:37:31,R_voU1RnHm9aPnqz7,NaN,NaN,NaN,NaN,35.949997,-78.961601,anonymous,EN,Gate 48 (DU_11_G48_C82),2018-09-01 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,Robin Franklin,Cathy Brennan,NaN,Sunny,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We saw an American Toad on our walk out!,NaN,F_2D6LnJrMqUw4S5r,TransecT-11 090118.pdf,3053261,application/pdf,NaN,NaN
5,2018-09-01 17:54:29,2018-09-01 18:22:38,IP Address,174.109.75.84,100,1688,True,2018-09-01 18:22:41,R_dbTWfk6WyKLsaCR,NaN,NaN,NaN,NaN,36.037796,-78.985802,anonymous,EN,Gate 4 (DU_1_G4_C52),2018-09-01 00:00:00,10:00am - 11:00am,Citizen Scientist,NaN,Barb Dietsch,Richard McFall,NaN,Mostly Sunny,84,NaN,NaN,Yes,NaN,NaN,Smooth Earth Snake (Virginia valeriae),W-5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_2pWwQEoHXbWWCi6,DU_1_G4_Wood5_1Sept2018.jpg,305093,image/jpeg,Stations W1 and W6 are so rotten that the turn...,NaN,F_2wuwkL2RXkSZ1Ah,DU_1_G4_SheeT-1Sept2018.jpg,206826,image/jpeg,NaN,NaN
6,2018-09-02 07:31:47,2018-09-02 07:39:34,IP Address,45.37.182.86,100,467,True,2018-09-02 07:39:36,R_3nrrdY9sKDV8361,NaN,NaN,NaN,NaN,35.889603,-78.9244,anonymous,EN,Gate 48 (DU_12_G48_C76),2018-09-01 00:00:00,2:00pm - 3:00pm,Citizen Scientist,NaN,Amber Meade,Jason Nichols,NaN,Mostly Sunny,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"When looking for W8, we found a very rotted bo...",NaN,F_2xRbqkhTEbJz2Nd,Herp sheet 9-1-18.jpg,35288,image/jpeg,NaN,NaN

### 2019 S1+S2

In [13]:
S1_2019 = S1_2019.drop(S1_2019.index[[0, 1]])
#add administrative comments
S1_2019.rename(columns={'Response ID' : 'Response_ID',\
                                  'Which transect did you survey?' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)' : 'Start_time',\
                                  'Are you a Citizen Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Info - Recorder (you)" : 'Observer',\
                                  "Observer Info - Other Observers" : 'Other_Observers',\
                                  'Air Temperature (Â°F)' : 'Temperature',\
                                  'What was the weather like?' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes and transect conditions can be submitted at the end).' : 'Flag_details',\
                                  'Upload a ZIP file of all of your photos: - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name' : 'Upload_sheet',\
                                  'Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.' : 'Comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_5_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_5_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_6_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_6_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_7_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_7_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_8_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_8_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_9_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_9_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 10')+1]: 'SP_10_Cover_ID', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 10')+2]: 'SP_10_Total', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 10')+3]: 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S1_2019.columns[S1_2019.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_13_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_13_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_14_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_14_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.13': 'SP_15_Cover_ID', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.13': 'SP_15_Total', \
                                  'Observation of Species\n\nCover ID should be coded "Transect Short Code_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).13': 'SP_15_Photo',\
                                  'Unnamed: 139': 'Extra photo 10'}, inplace=True)

In [14]:
new_column_name = 'Administrative_comments'
insert_position = S1_2019.columns.get_loc('Comments') + 1
S1_2019.insert(insert_position, new_column_name, np.nan)

In [15]:
S1_2019.head()

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response_ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Transect_ID,Date,Start_time,Affiliation,Community_team,Email,Observer,Other_Observers,Temperature,Sky_condition,Complete_transect,Complete_reason,Herp_obs,Flag,Flag_details,SP_1,SP_1_Cover_ID,SP_1_Total,SP_1_Photo,SP_2,SP_2_Cover_ID,SP_2_Total,SP_2_Photo,SP_3,SP_3_Cover_ID,SP_3_Total,SP_3_Photo,SP_4,SP_4_Cover_ID,SP_4_Total,SP_4_Photo,SP_5,SP_5_Cover_ID,SP_5_Total,SP_5_Photo,Record more Species/Occurrences?,SP_6,SP_6_Cover_ID,SP_6_Total,SP_6_Photo,SP_7,SP_7_Cover_ID,SP_7_Total,SP_7_Photo,SP_8,SP_8_Cover_ID,SP_8_Total,SP_8_Photo,SP_9,SP_9_Cover_ID,SP_9_Total,SP_9_Photo,SP_10,SP_10_Cover_ID,SP_10_Total,SP_10_Photo,Record more Species/Occurrences?.1,SP_11,SP_11_Cover_ID,SP_11_Total,SP_11_Photo,SP_12,SP_12_Cover_ID,SP_12_Total,SP_12_Photo,SP_13,SP_13_Cover_ID,SP_13_Total,SP_13_Photo,SP_14,SP_14_Cover_ID,SP_14_Total,SP_14_Photo,SP_15,SP_15_Cover_ID,SP_15_Total,SP_15_Photo,Upload a ZIP file of all of your photos: - Id,Upload_photo,Upload a ZIP file of all of your photos: - Size,Upload a ZIP file of all of your photos: - Type,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Id,Upload_sheet,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Size,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Type,Comments,Administrative_comments,Extra photo 1,Extra photo 1.1,Extra photo 1.2,Extra photo 1.3,Extra photo 2,Extra photo 2.1,Extra photo 2.2,Extra photo 2.3,Extra photo 3,Extra photo 3.1,Extra photo 3.2,Extra photo 3.3,Extra photo 4,Extra photo 4.1,Extra photo 4.2,Extra photo 4.3,Extra photo 5,Extra photo 5.1,Extra photo 5.2,Extra photo 5.3,Extra photo 6,Extra photo 6.1,Extra photo 6.2,Extra photo 6.3,Extra photo 7,Extra photo 7.1,Extra photo 7.2,Extra photo 7.3,Extra photo 8,Extra photo 8.1,Extra photo 8.2,Extra photo 8.3,Extra photo 9,Extra photo 9.1,Extra photo 9.2,Extra photo 9.3,Extra photo 10
2,2019-03-07 08:55:27,2019-03-07 09:13:18,IP Address,71.69.176.16,100,1071,True,2019-03-07 09:13:20,R_3KrujJRAZWwnk0a,NaN,NaN,NaN,NaN,36.075607,-79.0914,anonymous,EN,Gate 22 (DU_13_G22_C85),2019-03-06 00:00:00,4:00pm,Citizen Scientist,NaN,NaN,Bill Boyarsky,Kristen Orr,41,Sunny,Yes,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_1r825mfJDj9yoZA,DU_13_G22_C85 March 6 Count.pdf,84965,application/pdf,NaN,Found rodents (mole/shrew/vole?) under 2 of th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-03-27 14:25:28,2019-03-27 14:30:07,IP Address,152.3.3.112,100,278,True,2019-03-27 14:30:10,R_2VxRzHD85uTCfQm,NaN,NaN,NaN,NaN,35.996704,-78.896599,anonymous,EN,Gate 48_1 (DU_12_G48_C76),2019-03-08 00:00:00,4:00pm,Citizen Scientist,NaN,NaN,Hannah Royal,Susan Pratt,48,Cloudy,Yes,NaN,Yes,NaN,NaN,White-spotted Slimy Salamander (Plethodon cyli...,T-5,1,NaN,White-spotted Slimy Salamander (Plethodon cyli...,W-9,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_2xKNFufG5uOzcKp,IMG_9656.JPG,6091183,image/jpeg,F_1Q5vkfRuI72TvMU,Form 2.jpg,107594,image/jpeg,NaN,This specimen was huge!,F_XGpMTcCvC5OKufT,IMG_9652.JPG,6621255,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-03-09 16:07:59,2019-03-09 16:22:42,IP Address,71.229.50.39,100,882,True,2019-03-09 16:22:45,R_2a8MenVAW2Q9Z17,NaN,NaN,NaN,NaN,32.038803,-81.121902,anonymous,EN,Gate C-1 (DU_4_GC_C61),2019-03-08 00:00:00,11:00am,Participating in a Duke class,NaN,NaN,Nicki Cagle,Class,46,Cloudy,Yes,NaN,Yes,NaN,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-1,4,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-1,3,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-3,1,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-6,1,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-6,2,NaN,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-8,1,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_1gj2qWjEgZk84vQ,IMG_20190309_181818.jpg,3266145,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2019-03-27 14:17:40,2019-03-27 14:22:11,IP Address,152.3.3.112,100,271,True,2019-03-27 14:22:12,R_3ekHVfb9Cc2Pk5B,NaN,NaN,NaN,NaN,35.996704,-78.896599,anonymous,EN,Gate 48_2 (DU_11_G48_C82),2019-03-08 00:00:00,4:00pm,Citizen Scientist,NaN,NaN,Hannah Royal,Susan Pratt,48,Cloudy,Yes,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_WCK9DtuVimCn0TD,form.jpg,107935,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2019-03-17 09:37:10,2019-03-17 10:00:05,IP Address,76.182.99.56,100,1374,True,2019-03-17 10:00:26,R_1JQ4pgiAXI3xoa3,NaN,NaN,NaN,NaN,36.022903,-78.946404,anonymous,EN,Gate 8 (DU_5_G8_C62),2019-03-10 00:00:00,1:00pm,Citizen Scientist,NaN,NaN,Kathy Roth,Ed Cerne,66,Cloudy,Yes,NaN,Yes,NaN,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-1,1,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-1,1,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-3,1,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-7,1,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-7,1,NaN,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-8,3,NaN,Worm Snake (Carphophis amoenus),W-8,1,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-9,2,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-10,1,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-10,2.0,NaN,NaN,Worm Snake (Carphophis amoenus),T-5,1,NaN,Worm Snake (Carphophis amoenus),T-5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_1nZpuZe4YFzTJTY,redbackedsalamanderRedmorph_8_W1.JPEG,1335533,image/jpeg,F_ONhCOqG557BINjP,3.10.19 Data Sheet Gate 8.JPG,2822838,image/jpeg,NaN,A W7 photo shows a redbacked salamander Red mo...,F_2Y4APYXGGUlArFA,redbackedsalamanderblackmorph_8_W1.JPEG,1279302,image/jpeg,F_UAB6Zm1swWtgiVX,redbackedsalamanderBlackmorph_8_W3.JPEG,1210893,image/jpeg,F_3hDzLVZb5fe3Jtf,redbackedsalamanderRedmorph_8_W7.JPEG,1220151,image/jpeg,F_24OXKpokFnC8Nuy,redbackedsalamanderBlackmorph_8_W7.JPEG,1244039,image/jpeg,F_2f2rqUvN5z0oJ0B,redbackedsalamanderRedmorph_8_W8.JPEG,1020781,image/jpeg,F_3qVfGZWU9wYfFQo,wormsnake_8_W8.JPEG,992095,image/jpeg,F_szMsIxnBFMzPx6h,redbackedsalamanderRedmorph_8_W9.JPEG,1591035,image/jpeg,F_1hQ2WjWGfGvyhZf,redbackedsalamanderRedmorph_8_W10.JPEG,814871,image/jpeg,F_3LYJeEagpCvTKPq,wormsnake_8_T5.JPEG,780116,image/jpeg

In [16]:
remove_position = S1_2019.columns.get_loc('Administrative_comments')+1
S1_2019.drop(S1_2019.columns[[remove_position + 1, remove_position + 2, remove_position + 3, remove_position + 5,remove_position + 6,remove_position + 7, remove_position + 9,remove_position + 10,remove_position + 11, remove_position + 13,remove_position + 14,remove_position + 15,remove_position + 17,remove_position + 18,remove_position + 19,remove_position + 21,remove_position + 22,remove_position + 23,remove_position + 25,remove_position + 26,remove_position + 27,remove_position + 29,remove_position + 30,remove_position + 31,remove_position + 33,remove_position + 34,remove_position + 35]], axis=1, inplace=True)

In [17]:
"""S2_2019.rename(columns={'Response ID' : 'Response_ID',\
                                  'Which transect did you survey?' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)' : 'Start_time',\
                                  'Are you a Citizen Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Info - Recorder (you)" : 'Observer',\
                                  "Observer Info - Other Observers" : 'Other_Observers',\
                                  'Air Temperature (Â°F)' : 'Temperature',\
                                  'What was the weather like?' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes and transect conditions can be submitted at the end).' : 'Flag_details',\
                                  'Upload a ZIP file of all of your photos: - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name' : 'Upload_sheet',\
                                  'Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.' : 'Comments',\
                                  'Observation of Species - Cover ID for Occurrence 1': 'SP_1_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 1': 'SP_1_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 1': 'SP_1_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 1': 'SP_1_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 1': 'SP_1_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 1': 'SP_1_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 2': 'SP_2_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 2': 'SP_2_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 2': 'SP_2_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 3': 'SP_3_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 3': 'SP_3_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 3': 'SP_3_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 4': 'SP_4_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 4': 'SP_4_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 4': 'SP_4_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 5': 'SP_5_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 5': 'SP_5_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 5': 'SP_5_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 6': 'SP_6_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 6': 'SP_6_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 6': 'SP_6_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 7': 'SP_7_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 7': 'SP_7_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 7': 'SP_7_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 8': 'SP_8_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 8': 'SP_8_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 8': 'SP_8_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 9': 'SP_9_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 9': 'SP_9_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 9': 'SP_9_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 10': 'SP_10_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 10': 'SP_10_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 10': 'SP_10_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 11': 'SP_11_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 11': 'SP_11_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 11': 'SP_11_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 12': 'SP_12_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 12': 'SP_12_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 12': 'SP_12_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 12': 'SP_13_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 12': 'SP_13_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 13': 'SP_13_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 14': 'SP_14_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 14': 'SP_14_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 14': 'SP_14_Photo', \
                                  'Observation of Species - Cover ID for Occurrence 15': 'SP_15_Cover_ID', \
                                  'Observation of Species - Total for Occurrence 15': 'SP_15_Total', \
                                  'Observation of Species - Photo (y/n) for Occurrence 15': 'SP_15_Photo',},inplace=True)"""

'S2_2019.rename(columns={\'Response ID\' : \'Response_ID\',                                  \'Which transect did you survey?\' : \'Transect_ID\',                                  \'Survey Date (mm/dd/yyyy)\' : \'Date\',                                  \'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)\' : \'Start_time\',                                  \'Are you a Citizen Scientist or are you participating in a Duke class?\' : \'Affiliation\',                                  \'What team was scheduled for this transect?\' : \'Community_team\',                                  \'Email Address\' : \'Email\',                                  "Observer Info - Recorder (you)" : \'Observer\',                                  "Observer Info - Other Observers" : \'Other_Observers\',                                  \'Air Temperature (Â°F)\' : \'Temperature\',                                  \'What was the weather like?\' : \'Sky_condition\',                                  \'Did you check all 15 pieces of cover along this transect?\' : \'Complete_transect\',                                  \'If not, which pieces did you not check and why?\' : \'Complete_reason\',                                  \'Did you find any herps at this transect?\' : \'Herp_obs\',                                  \'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.\' : \'Flag\',                                  \'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes and transect conditions can be submitted at the end).\' : \'Flag_details\',                                  \'Upload a ZIP file of all of your photos: - Name\' : \'Upload_photo\' ,                                  \'Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name\' : \'Upload_sheet\',                                  \'Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.\' : \'Comments\',                                  \'Observation of Species - Cover ID for Occurrence 1\': \'SP_1_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 1\': \'SP_1_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 1\': \'SP_1_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 1\': \'SP_1_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 1\': \'SP_1_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 1\': \'SP_1_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 2\': \'SP_2_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 2\': \'SP_2_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 2\': \'SP_2_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 3\': \'SP_3_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 3\': \'SP_3_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 3\': \'SP_3_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 4\': \'SP_4_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 4\': \'SP_4_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 4\': \'SP_4_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 5\': \'SP_5_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 5\': \'SP_5_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 5\': \'SP_5_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 6\': \'SP_6_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 6\': \'SP_6_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 6\': \'SP_6_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 7\': \'SP_7_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 7\': \'SP_7_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 7\': \'SP_7_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 8\': \'SP_8_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 8\': \'SP_8_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 8\': \'SP_8_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 9\': \'SP_9_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 9\': \'SP_9_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 9\': \'SP_9_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 10\': \'SP_10_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 10\': \'SP_10_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 10\': \'SP_10_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 11\': \'SP_11_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 11\': \'SP_11_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 11\': \'SP_11_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 12\': \'SP_12_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 12\': \'SP_12_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 12\': \'SP_12_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 12\': \'SP_13_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 12\': \'SP_13_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 13\': \'SP_13_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 14\': \'SP_14_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 14\': \'SP_14_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 14\': \'SP_14_Photo\',                                   \'Observation of Species - Cover ID for Occurrence 15\': \'SP_15_Cover_ID\',                                   \'Observation of Species - Total for Occurrence 15\': \'SP_15_Total\',                                   \'Observation of Species - Photo (y/n) for Occurrence 15\': \'SP_15_Photo\',},inplace=True)'

### 2020 S1

In [18]:
S1_2020.rename(columns={'Transect ID' : 'Transect_ID',\
                                  'Response ID' : 'Response_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time\n\nRound to the closest hour.' : 'Start_time',\
                                  'Are you a Community Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Names - Recorder (you)" : 'Observer',\
                                  "Observer Names - Other Observer(s)" : 'Other_Observers',\
                                  'Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Â°F" or "degrees".' : 'Temperature',\
                                  'Sky Condition / Precipitation Status' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources, post in the @General or @Photos channel in MSTeams, or ask for support from other volunteers. At that point, if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes can be submitted at the end).' : 'Flag_details',\
                                  'Upload Your Photos - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please) - Name' : 'Upload_sheet',\
                                  'Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). If you are a Community Scientist volunteer and have "Damage to report" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams. If you are a student/staff/researcher, please put it here.' : 'Comments',\
                                  'Administrative Comments' : 'Administrative_comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3': 'SP_5_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3': 'SP_5_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_6_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_6_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_7_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_7_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_8_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_8_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_9_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_9_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_10_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_10_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S1_2020.columns[S1_2020.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10': 'SP_13_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10': 'SP_13_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_14_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_14_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_15_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_15_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_15_Photo'}, inplace=True)

### 2021 S1

In [19]:
S1_2021.rename(columns={'Response ID' : 'Response_ID',\
                                  'Transect ID' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time (12hr format, ex. 1:00 PM or 11:00 AM)' : 'Start_time',\
                                  'Are you a Citizen Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                   'Email Address' : 'Email',\
                                  "Observer Names - Recorder (you)" : 'Observer',\
                                  "Observer Names - Other Observers" : 'Other_Observers',\
                                  'Temperature (Â°F)' : 'Temperature',\
                                  'Sky Condition / Precipitation Status' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources and our Facebook group to do your best. Only if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes can be submitted at the end).' : 'Flag_details',\
                                  'Upload a ZIP file of all of your photos: - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG. please) - Name' : 'Upload_sheet',\
                                  'Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). If you have "Damage to report" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams.' : 'Comments',\
                                  'Administrative Notes' : 'Administrative_comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3': 'SP_5_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3': 'SP_5_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_6_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_6_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_7_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_7_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_8_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_8_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_9_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_9_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_10_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_10_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S1_2021.columns[S1_2021.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10': 'SP_13_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10': 'SP_13_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_14_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_14_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_15_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_15_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_15_Photo'}, inplace=True)

### 2022 S1

In [20]:
S1_2022.rename(columns={'Response ID' : 'Response_ID',\
                                  'Transect ID' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time\n\nRound to the closest hour.' : 'Start_time',\
                                  'Are you a Community Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Names - Recorder (you)" : 'Observer',\
                                  "Observer Names - Other Observer(s)" : 'Other_Observers',\
                                  'Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Â°F" or "degrees".' : 'Temperature',\
                                  'Sky Condition / Precipitation Status' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps at this transect?' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources, post in the @General or @Photos channel in MSTeams, or ask for support from other volunteers. At that point, if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes can be submitted at the end).' : 'Flag_details',\
                                  'Upload Your Photos - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please) - Name' : 'Upload_sheet',\
                                  'Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). If you are a Community Scientist volunteer and have "Damage to report" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams. If you are a student/staff/researcher, please put it here.' : 'Comments',\
                                  'Administrative Comments' : 'Administrative_comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3': 'SP_5_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3': 'SP_5_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_6_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_6_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_7_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_7_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_8_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_8_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_9_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_9_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_10_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_10_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S1_2022.columns[S1_2022.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10': 'SP_13_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10': 'SP_13_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_14_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_14_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_15_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_15_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_15_Photo'}, inplace=True)

### 2022 S2

In [21]:
S2_2022.rename(columns={'Response ID' : 'Response_ID',\
                                  'Transect ID' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time\n\nRound to the closest hour.' : 'Start_time',\
                                  'Are you a Community Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Names - Recorder (you)" : 'Observer',\
                                  "Observer Names - Other Observer(s)" : 'Other_Observers',\
                                  'Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Â°F" or "degrees".' : 'Temperature',\
                                  'Sky Condition / Precipitation Status' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps OR ants at this transect?\n\n\n\nAs of July 2022: We are beginning to take data about ant colonies found beneath our transect coverboards in order to help us answer the question: "does the presence of ant colonies at a coverboard affect the presence of herpetofauna there?" Please indicate YES below if you found ant colonies at one or more coverboards, even if you didn\'t find any herps.' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, please use your resources, post in the @General or @Photos channel in MSTeams, or ask for support from other volunteers. At that point, if you are still unsure, you may "flag" your data for our team to review.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes can be submitted at the end).' : 'Flag_details',\
                                  'Upload Your Photos - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT â€“ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: "2022.04.27_48-2_Datasheet.pdf" - Name' : 'Upload_sheet',\
                                  'Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). If you are a Community Scientist volunteer and have "Damage to report" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams. If you are a student/staff/researcher, please put it here.' : 'Comments',\
                                  'Administrative Comments' : 'Administrative_comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3': 'SP_5_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3': 'SP_5_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_6_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_6_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_7_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_7_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_8_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_8_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_9_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_9_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_10_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_10_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S2_2022.columns[S2_2022.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10': 'SP_13_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10': 'SP_13_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_14_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_14_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_15_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_15_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_15_Photo'}, inplace=True)

### 2023 S1

In [22]:
S1_2023.rename(columns={'Response ID' : 'Response_ID',\
                                  'Transect ID' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time\n\nRound to the closest hour.' : 'Start_time',\
                                  'Are you a Community Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Names\n\nPlease include all Observers' full names, including First and Last names. - Recorder (you)" : 'Observer',\
                                  "Observer Names\n\nPlease include all Observers' full names, including First and Last names. - Other Observer(s)" : 'Other_Observers',\
                                  'Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Â°F" or "degrees".' : 'Temperature',\
                                  'Sky Condition / Precipitation Status' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps OR ants at this transect?\n\nAs of July 2022: We are beginning to take data about ant colonies found beneath our transect coverboards in order to help us answer the question: "does the presence of ant colonies at a coverboard affect the presence of herpetofauna there?" Please indicate YES below if you found ant colonies at any of the coverboards, even if you didn\'t find any herps.' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, you may "flag" your data for Duke Forest staff to review.\n\nFor Community Scientists: Please use your resources, post in the @General or @Photos channel in MSTeams, or ask for support from other volunteers. At that point, if you are still unsure, you may "flag" your data.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes/comments can be submitted at the end of this survey).' : 'Flag_details',\
                                  'Upload Your Photos - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT â€“ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: "2022.04.27_48-2_Datasheet.pdf" - Name' : 'Upload_sheet',\
                                  'Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). \n\n\n\nIf you are a Community Scientist volunteer and have "Damage to report" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams. If you are a student/staff/researcher, please put it here.' : 'Comments',\
                                  'Administrative Comments' : 'Administrative_comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3': 'SP_5_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3': 'SP_5_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_6_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_6_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_7_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_7_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_8_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_8_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_9_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_9_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_10_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_10_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S1_2023.columns[S1_2023.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10': 'SP_13_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10': 'SP_13_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_14_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_14_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_15_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_15_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_15_Photo'}, inplace=True)

### 2023 S2

In [23]:
S2_2023.rename(columns={'Response ID' : 'Response_ID',\
                                  'Transect ID' : 'Transect_ID',\
                                  'Survey Date (mm/dd/yyyy)' : 'Date',\
                                  'Survey Start Time\n\nRound to the closest hour.' : 'Start_time',\
                                  'Are you a Community Scientist or are you participating in a Duke class?' : 'Affiliation',\
                                  'What team was scheduled for this transect?' : 'Community_team',\
                                  'Email Address' : 'Email',\
                                  "Observer Names\n\nPlease include all Observers' full names, including First and Last names. - Recorder (you)" : 'Observer',\
                                  "Observer Names\n\nPlease include all Observers' full names, including First and Last names. - Other Observer(s)" : 'Other_Observers',\
                                  'Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Â°F" or "degrees".' : 'Temperature',\
                                  'Sky Condition / Precipitation Status' : 'Sky_condition',\
                                  'Did you check all 15 pieces of cover along this transect?' : 'Complete_transect',\
                                  'If not, which pieces did you not check and why?' : 'Complete_reason',\
                                  'Did you find any herps OR ants at this transect?\n\nAs of July 2022: We are beginning to take data about ant colonies found beneath our transect coverboards in order to help us answer the question: "does the presence of ant colonies at a coverboard affect the presence of herpetofauna there?" Please indicate YES below if you found ant colonies at any of the coverboards, even if you didn\'t find any herps.' : 'Herp_obs',\
                                  'Species ID Support\n\nIf you had difficulty with identification of any species in any occurrence, you may "flag" your data for Duke Forest staff to review.\n\nFor Community Scientists: Please use your resources, post in the @General or @Photos channel in MSTeams, or ask for support from other volunteers. At that point, if you are still unsure, you may "flag" your data.' : 'Flag',\
                                  'If you had ID issues, please write any notes here to inform the review process. Be specific with which occurrence (cover board, guessed species, picture)  you are referring.\n\n(General notes/comments can be submitted at the end of this survey).' : 'Flag_details',\
                                  'Upload Your Photos - Name' : 'Upload_photo' ,\
                                  'Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT â€“ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: "2022.04.27_48-2_Datasheet.pdf" - Name' : 'Upload_sheet',\
                                  'Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). \n\n\n\nIf you are a Community Scientist volunteer and have "Damage to report" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams. If you are a student/staff/researcher, please put it here.' : 'Comments',\
                                  'Administrative Comments' : 'Administrative_comments',\
                                  'Species/Occurrence 1': 'SP_1',\
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 1')+1]: 'SP_1_Cover_ID', \
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 1')+2]: 'SP_1_Total', \
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 1')+3]: 'SP_1_Photo', \
                                  'Species/Occurrence 2': 'SP_2',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.1': 'SP_2_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.1': 'SP_2_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).1': 'SP_2_Photo', \
                                  'Species/Occurrence 3': 'SP_3',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.2': 'SP_3_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.2': 'SP_3_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).2': 'SP_3_Photo', \
                                  'Species/Occurrence 4': 'SP_4',\
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 4')+1]: 'SP_4_Cover_ID', \
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 4')+2]: 'SP_4_Total', \
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 4')+3]: 'SP_4_Photo', \
                                  'Species/Occurrence 5': 'SP_5',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.3': 'SP_5_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.3': 'SP_5_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).3': 'SP_5_Photo', \
                                  'Species/Occurrence 6': 'SP_6',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.4': 'SP_6_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.4': 'SP_6_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).4': 'SP_6_Photo', \
                                  'Species/Occurrence 7': 'SP_7',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.5': 'SP_7_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.5': 'SP_7_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).5': 'SP_7_Photo', \
                                  'Species/Occurrence 8': 'SP_8',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.6': 'SP_8_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.6': 'SP_8_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).6': 'SP_8_Photo', \
                                  'Species/Occurrence 9': 'SP_9',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.7': 'SP_9_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.7': 'SP_9_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).7': 'SP_9_Photo', \
                                  'Species/Occurrence 10': 'SP_10',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.8': 'SP_10_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.8': 'SP_10_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).8': 'SP_10_Photo', \
                                  'Species/Occurrence 11': 'SP_11',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.9': 'SP_11_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.9': 'SP_11_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).9': 'SP_11_Photo', \
                                  'Species/Occurrence 12': 'SP_12',\
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 12')+1]: 'SP_12_Cover_ID', \
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 12')+2]: 'SP_12_Total', \
                                  S2_2023.columns[S2_2023.columns.get_loc('Species/Occurrence 12')+3]: 'SP_12_Photo', \
                                  'Species/Occurrence 13': 'SP_13',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.10': 'SP_13_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.10': 'SP_13_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).10': 'SP_13_Photo', \
                                  'Species/Occurrence 14': 'SP_14',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.11': 'SP_14_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11': 'SP_14_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11': 'SP_14_Photo', \
                                  'Species/Occurrence 15': 'SP_15',\
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12': 'SP_15_Cover_ID', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12': 'SP_15_Total', \
                                  'Observation of Species\nCover ID should be coded "Short Transect ID_Cover ID" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12': 'SP_15_Photo'}, inplace=True)

## Obsolete Data Remover Function

In [24]:
def obsolete_remover(data):
    # Define columns to exclude from dropping
    exclude_from_dropping = ['Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team',\
                             'Email', "Observer", "Other_Observers", 'Temperature', 'Sky_condition', 'Complete_transect',\
                             'Complete_reason', 'Herp_obs', 'Flag', 'Flag_details', 'SP_1', 'SP_1_Cover_ID',\
                             'SP_1_Total', 'SP_1_Photo', 'SP_2', 'SP_2_Cover_ID', 'SP_2_Total', 'SP_2_Photo',\
                             'SP_3', 'SP_3_Cover_ID', 'SP_3_Total', 'SP_3_Photo', 'SP_4', 'SP_4_Cover_ID',\
                             'SP_4_Total', 'SP_4_Photo', 'SP_5', 'SP_5_Cover_ID', 'SP_5_Total', 'SP_5_Photo', 'SP_6',\
                             'SP_6_Cover_ID', 'SP_6_Total','SP_6_Photo', 'SP_7', 'SP_7_Cover_ID', 'SP_7_Total',\
                             'SP_7_Photo', 'SP_8', 'SP_8_Cover_ID', 'SP_8_Total', 'SP_8_Photo', 'SP_9','SP_9_Cover_ID',\
                             'SP_9_Total', 'SP_9_Photo', 'SP_10', 'SP_10_Cover_ID', 'SP_10_Total', 'SP_10_Photo',\
                             'SP_11', 'SP_11_Cover_ID', 'SP_11_Total', 'SP_11_Photo', 'SP_12', 'SP_12_Cover_ID',\
                             'SP_12_Total', 'SP_12_Photo', 'SP_13', 'SP_13_Cover_ID', 'SP_13_Total', 'SP_13_Photo',\
                             'SP_14', 'SP_14_Cover_ID', 'SP_14_Total', 'SP_14_Photo', 'SP_15', 'SP_15_Cover_ID',\
                             'SP_15_Total', 'SP_15_Photo','Upload_photo','Upload_sheet', 'Comments', 'Administrative_comments']
    
    # Drop the rest
    data = data[exclude_from_dropping]
    
    return data

In [25]:
Pre_2018 = obsolete_remover(Pre_2018)

S2_2018_cols = ['Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team',\
                 'Email', "Observer", "Other_Observers", 'Temperature', 'Sky_condition', 'Complete_transect',\
                 'Complete_reason', 'Herp_obs', 'Flag', 'Flag_details', 'SP_1', 'SP_1_Cover_ID',\
                 'SP_1_Total', 'SP_1_Photo', 'SP_2', 'SP_2_Cover_ID', 'SP_2_Total', 'SP_2_Photo',\
                 'SP_3', 'SP_3_Cover_ID', 'SP_3_Total', 'SP_3_Photo', 'SP_4', 'SP_4_Cover_ID',\
                 'SP_4_Total', 'SP_4_Photo', 'SP_5', 'SP_5_Cover_ID', 'SP_5_Total', 'SP_5_Photo', 'SP_6',\
                 'SP_6_Cover_ID', 'SP_6_Total','SP_6_Photo', 'SP_7', 'SP_7_Cover_ID', 'SP_7_Total',\
                 'SP_7_Photo', 'SP_8', 'SP_8_Cover_ID', 'SP_8_Total', 'SP_8_Photo', 'SP_9','SP_9_Cover_ID',\
                 'SP_9_Total', 'SP_9_Photo', 'SP_10', 'SP_10_Cover_ID', 'SP_10_Total', 'SP_10_Photo',\
                 'SP_11', 'SP_11_Cover_ID', 'SP_11_Total', 'SP_11_Photo', 'SP_12', 'SP_12_Cover_ID',\
                 'SP_12_Total', 'SP_12_Photo', 'SP_13', 'SP_13_Cover_ID', 'SP_13_Total', 'SP_13_Photo',\
                 'SP_14', 'SP_14_Cover_ID', 'SP_14_Total', 'SP_14_Photo', 'SP_15', 'SP_15_Cover_ID',\
                 'SP_15_Total', 'SP_15_Photo','Upload_photo','Upload_sheet', 'Comments', 'Administrative_comments',\
                 'Extra photo 1', 'Extra photo 2']
S2_2018 = S2_2018[S2_2018_cols]


S1_2019_cols = ['Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team',\
                 'Email', "Observer", "Other_Observers", 'Temperature', 'Sky_condition', 'Complete_transect',\
                 'Complete_reason', 'Herp_obs', 'Flag', 'Flag_details', 'SP_1', 'SP_1_Cover_ID',\
                 'SP_1_Total', 'SP_1_Photo', 'SP_2', 'SP_2_Cover_ID', 'SP_2_Total', 'SP_2_Photo',\
                 'SP_3', 'SP_3_Cover_ID', 'SP_3_Total', 'SP_3_Photo', 'SP_4', 'SP_4_Cover_ID',\
                 'SP_4_Total', 'SP_4_Photo', 'SP_5', 'SP_5_Cover_ID', 'SP_5_Total', 'SP_5_Photo', 'SP_6',\
                 'SP_6_Cover_ID', 'SP_6_Total','SP_6_Photo', 'SP_7', 'SP_7_Cover_ID', 'SP_7_Total',\
                 'SP_7_Photo', 'SP_8', 'SP_8_Cover_ID', 'SP_8_Total', 'SP_8_Photo', 'SP_9','SP_9_Cover_ID',\
                 'SP_9_Total', 'SP_9_Photo', 'SP_10', 'SP_10_Cover_ID', 'SP_10_Total', 'SP_10_Photo',\
                 'SP_11', 'SP_11_Cover_ID', 'SP_11_Total', 'SP_11_Photo', 'SP_12', 'SP_12_Cover_ID',\
                 'SP_12_Total', 'SP_12_Photo', 'SP_13', 'SP_13_Cover_ID', 'SP_13_Total', 'SP_13_Photo',\
                 'SP_14', 'SP_14_Cover_ID', 'SP_14_Total', 'SP_14_Photo', 'SP_15', 'SP_15_Cover_ID',\
                 'SP_15_Total', 'SP_15_Photo','Upload_photo','Upload_sheet', 'Comments', 'Administrative_comments',\
                 'Extra photo 1', 'Extra photo 2', 'Extra photo 3', 'Extra photo 4', 'Extra photo 5', 'Extra photo 6', 'Extra photo 7', 'Extra photo 8', 'Extra photo 9', 'Extra photo 10']
S1_2019 = S1_2019[S1_2019_cols]

S1_2020 = obsolete_remover(S1_2020)
S1_2021 = obsolete_remover(S1_2021)
S1_2022 = obsolete_remover(S1_2022)
S2_2022 = obsolete_remover(S2_2022)
S1_2023 = obsolete_remover(S1_2023)
S2_2023 = obsolete_remover(S2_2023)

In [26]:
S2_2018.head()

,Response_ID,Transect_ID,Date,Start_time,Affiliation,Community_team,Email,Observer,Other_Observers,Temperature,Sky_condition,Complete_transect,Complete_reason,Herp_obs,Flag,Flag_details,SP_1,SP_1_Cover_ID,SP_1_Total,SP_1_Photo,SP_2,SP_2_Cover_ID,SP_2_Total,SP_2_Photo,SP_3,SP_3_Cover_ID,SP_3_Total,SP_3_Photo,SP_4,SP_4_Cover_ID,SP_4_Total,SP_4_Photo,SP_5,SP_5_Cover_ID,SP_5_Total,SP_5_Photo,SP_6,SP_6_Cover_ID,SP_6_Total,SP_6_Photo,SP_7,SP_7_Cover_ID,SP_7_Total,SP_7_Photo,SP_8,SP_8_Cover_ID,SP_8_Total,SP_8_Photo,SP_9,SP_9_Cover_ID,SP_9_Total,SP_9_Photo,SP_10,SP_10_Cover_ID,SP_10_Total,SP_10_Photo,SP_11,SP_11_Cover_ID,SP_11_Total,SP_11_Photo,SP_12,SP_12_Cover_ID,SP_12_Total,SP_12_Photo,SP_13,SP_13_Cover_ID,SP_13_Total,SP_13_Photo,SP_14,SP_14_Cover_ID,SP_14_Total,SP_14_Photo,SP_15,SP_15_Cover_ID,SP_15_Total,SP_15_Photo,Upload_photo,Upload_sheet,Comments,Administrative_comments,Extra photo 1,Extra photo 2
2,R_BDKkrLu1xspw7eh,Gate C-1 (DU_4_GC_C61),2018-08-28 00:00:00,3:00pm - 4:00pm,Citizen Scientist,NaN,NaN,"Cagle, Nicolette","Cagle, Grant",91,Mostly Sunny,NaN,NaN,Yes,NaN,NaN,Skink (Unidentified),W-6,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28Aug2018 Durham Duke Forest skink transect DU...,IMG_20180828_0002.pdf,NaN,NaN,NaN,NaN
3,R_3rSSt8H4V0qrxpg,Gate 8 (DU_5_G8_C62),2018-08-29 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,NaN,Richard DAngiolillo,Bill Boyarsky,76,Mostly Sunny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DU_5_G8_C62 Aug 29 2018.pdf,We were wondering if we might find more herps ...,NaN,NaN,NaN
4,R_voU1RnHm9aPnqz7,Gate 48 (DU_11_G48_C82),2018-09-01 00:00:00,9:00am - 10:00am,Citizen Scientist,NaN,NaN,Robin Franklin,Cathy Brennan,77,Sunny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TransecT-11 090118.pdf,We saw an American Toad on our walk out!,NaN,NaN,NaN
5,R_dbTWfk6WyKLsaCR,Gate 4 (DU_1_G4_C52),2018-09-01 00:00:00,10:00am - 11:00am,Citizen Scientist,NaN,NaN,Barb Dietsch,Richard McFall,84,Mostly Sunny,NaN,NaN,Yes,NaN,NaN,Smooth Earth Snake (Virginia valeriae),W-5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DU_1_G4_Wood5_1Sept2018.jpg,DU_1_G4_SheeT-1Sept2018.jpg,Stations W1 and W6 are so rotten that the turn...,NaN,NaN,NaN
6,R_3nrrdY9sKDV8361,Gate 48 (DU_12_G48_C76),2018-09-01 00:00:00,2:00pm - 3:00pm,Citizen Scientist,NaN,NaN,Amber Meade,Jason Nichols,89,Mostly Sunny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Herp sheet 9-1-18.jpg,"When looking for W8, we found a very rotted bo...",NaN,NaN,NaN

## Ant observations addition

In [27]:
def add_ant_obs(df):
    herp_obs_index = df.columns.get_loc('Herp_obs') + 1
    df.insert(herp_obs_index, 'Ant_obs', 'No')
    
    sp_columns = [f'SP_{i}' for i in range(1, 16)]

    # Update 'Ant_obs' column based on the presence of 'ant' in SP columns
    for index, row in df.iterrows():
        if any('ant' in str(row[sp_col]).lower() for sp_col in sp_columns):
            df.at[index, 'Ant_obs'] = 'Yes'

    return df

In [28]:
Pre_2018 = add_ant_obs(Pre_2018)
S2_2018 = add_ant_obs(S2_2018)
S1_2019 = add_ant_obs(S1_2019)
S1_2020 = add_ant_obs(S1_2020)
S1_2021 = add_ant_obs(S1_2021)
S1_2022 = add_ant_obs(S1_2022)
S2_2022 = add_ant_obs(S2_2022)
S1_2023 = add_ant_obs(S1_2023)
S2_2023 = add_ant_obs(S2_2023)

## Dead and Other animal addition

In [29]:
def dead_other_add(df):
    index = df.columns.get_loc('SP_15_Photo') + 1
    df.insert(index, 'Dead_animal', np.nan)

    index = df.columns.get_loc('SP_15_Photo') + 2
    df.insert(index, 'Dead_detail', np.nan)
    
    index = df.columns.get_loc('SP_15_Photo') + 3
    df.insert(index, 'Other_animal', np.nan)
    
    index = df.columns.get_loc('SP_15_Photo') + 4
    df.insert(index, 'Other_detail', np.nan)

    return df

In [30]:
Pre_2018 = dead_other_add(Pre_2018)
S2_2018 = dead_other_add(S2_2018)
S1_2019 = dead_other_add(S1_2019)
S1_2020 = dead_other_add(S1_2020)
S1_2021 = dead_other_add(S1_2021)
S1_2022 = dead_other_add(S1_2022)
S2_2022 = dead_other_add(S2_2022)
S1_2023 = dead_other_add(S1_2023)
S2_2023 = dead_other_add(S2_2023)

## WIDE TO LONG FUNCTION

In [31]:
def wide_to_long(df):
    new_rows = []
    for index, row in df.iterrows():
        herp_obs = row['Herp_obs']
        ant_obs = row['Ant_obs']
        if herp_obs == 'No' and ant_obs == 'No':
            # Include only the first SP observation
            new_row = row.copy()
            new_row['SP'] = row['SP_1']
            new_row['SP_Cover_ID'] = row['SP_1_Cover_ID']
            new_row['SP_Total'] = row['SP_1_Total']
            new_row['SP_Photo'] = row['SP_1_Photo']
            new_row['Dead_animal'] = np.nan
            new_row['Dead_detail'] = np.nan
            new_row['Other_animal'] = np.nan
            new_row['Other_detail'] = np.nan
            new_rows.append(new_row)
        else:
            # Include all non-NaN SP observations
            for i in range(1, 16):
                sp = row[f'SP_{i}']
                if pd.isna(sp):
                    continue
                new_row = row.copy()
                new_row['SP'] = row[f'SP_{i}']
                new_row['SP_Cover_ID'] = row[f'SP_{i}_Cover_ID']
                new_row['SP_Total'] = row[f'SP_{i}_Total']
                new_row['SP_Photo'] = row[f'SP_{i}_Photo']
                new_row['Dead_animal'] = np.nan  # Placeholder, update based on your logic
                new_row['Dead_detail'] = np.nan  # Placeholder, update based on your logic
                new_row['Other_animal'] = np.nan  # Placeholder, update based on your logic
                new_row['Other_detail'] = np.nan  # Placeholder, update based on your logic
                new_rows.append(new_row)

    # Create a new DataFrame from the new rows
    new_df = pd.DataFrame(new_rows)
    
    return new_df

In [32]:
Pre_2018 = wide_to_long(Pre_2018)
S2_2018 = wide_to_long(S2_2018)
S1_2019 = wide_to_long(S1_2019)
S1_2020 = wide_to_long(S1_2020)
S1_2021 = wide_to_long(S1_2021)
S1_2022 = wide_to_long(S1_2022)
S2_2022 = wide_to_long(S2_2022)
S1_2023 = wide_to_long(S1_2023)
S2_2023 = wide_to_long(S2_2023)

In [33]:
cols = [
        'Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team', 'Email', 'Observer', 
        'Other_Observers', 'Temperature', 'Sky_condition', 'Complete_transect', 'Complete_reason', 'Herp_obs', 'Ant_obs', 
        'Flag', 'Flag_details', 'SP', 'SP_Cover_ID', 'SP_Total', 'SP_Photo', 'Dead_animal', 'Dead_detail', 
        'Other_animal', 'Other_detail', 'Upload_photo', 'Upload_sheet', 'Comments', 'Administrative_comments'
    ]
Pre_2018 = Pre_2018[cols]
S1_2020 = S1_2020[cols]
S1_2021 = S1_2021[cols]
S1_2022 = S1_2022[cols]
S2_2022 = S2_2022[cols]
S1_2023 = S1_2023[cols]
S2_2023 = S2_2023[cols]


S1_2018_cols = [
        'Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team', 'Email', 'Observer', 
        'Other_Observers', 'Temperature', 'Sky_condition', 'Complete_transect', 'Complete_reason', 'Herp_obs', 'Ant_obs', 
        'Flag', 'Flag_details', 'SP', 'SP_Cover_ID', 'SP_Total', 'SP_Photo', 'Dead_animal', 'Dead_detail', 
        'Other_animal', 'Other_detail', 'Upload_photo', 'Upload_sheet', 'Comments', 'Administrative_comments',
        'Extra photo 1', 'Extra photo 2'
    ]
S2_2018 = S2_2018[S1_2018_cols]

S1_2019_cols = [
        'Response_ID', 'Transect_ID', 'Date', 'Start_time', 'Affiliation', 'Community_team', 'Email', 'Observer', 
        'Other_Observers', 'Temperature', 'Sky_condition', 'Complete_transect', 'Complete_reason', 'Herp_obs', 'Ant_obs', 
        'Flag', 'Flag_details', 'SP', 'SP_Cover_ID', 'SP_Total', 'SP_Photo', 'Dead_animal', 'Dead_detail', 
        'Other_animal', 'Other_detail', 'Upload_photo', 'Upload_sheet', 'Comments', 'Administrative_comments',
        'Extra photo 1', 'Extra photo 2', 'Extra photo 3','Extra photo 4', 'Extra photo 5','Extra photo 6', 'Extra photo 7','Extra photo 8','Extra photo 9','Extra photo 10'
    ]
S1_2019 = S1_2019[S1_2019_cols]

In [34]:
S1_2019.head()

,Response_ID,Transect_ID,Date,Start_time,Affiliation,Community_team,Email,Observer,Other_Observers,Temperature,Sky_condition,Complete_transect,Complete_reason,Herp_obs,Ant_obs,Flag,Flag_details,SP,SP_Cover_ID,SP_Total,SP_Photo,Dead_animal,Dead_detail,Other_animal,Other_detail,Upload_photo,Upload_sheet,Comments,Administrative_comments,Extra photo 1,Extra photo 2,Extra photo 3,Extra photo 4,Extra photo 5,Extra photo 6,Extra photo 7,Extra photo 8,Extra photo 9,Extra photo 10
2,R_3KrujJRAZWwnk0a,Gate 22 (DU_13_G22_C85),2019-03-06,4:00pm,Citizen Scientist,NaN,NaN,Bill Boyarsky,Kristen Orr,41,Sunny,Yes,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F_1r825mfJDj9yoZA,application/pdf,NaN,Found rodents (mole/shrew/vole?) under 2 of th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R_2VxRzHD85uTCfQm,Gate 48_1 (DU_12_G48_C76),2019-03-08,4:00pm,Citizen Scientist,NaN,NaN,Hannah Royal,Susan Pratt,48,Cloudy,Yes,NaN,Yes,No,NaN,NaN,White-spotted Slimy Salamander (Plethodon cyli...,T-5,1.0,NaN,NaN,NaN,NaN,NaN,F_2xKNFufG5uOzcKp,F_1Q5vkfRuI72TvMU,image/jpeg,NaN,This specimen was huge!,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R_2VxRzHD85uTCfQm,Gate 48_1 (DU_12_G48_C76),2019-03-08,4:00pm,Citizen Scientist,NaN,NaN,Hannah Royal,Susan Pratt,48,Cloudy,Yes,NaN,Yes,No,NaN,NaN,White-spotted Slimy Salamander (Plethodon cyli...,W-9,1.0,NaN,NaN,NaN,NaN,NaN,F_2xKNFufG5uOzcKp,F_1Q5vkfRuI72TvMU,image/jpeg,NaN,This specimen was huge!,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R_2a8MenVAW2Q9Z17,Gate C-1 (DU_4_GC_C61),2019-03-08,11:00am,Participating in a Duke class,NaN,NaN,Nicki Cagle,Class,46,Cloudy,Yes,NaN,Yes,No,NaN,NaN,Red-backed Salamander (Plethodon cinereus) - R...,W-1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,F_1gj2qWjEgZk84vQ,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R_2a8MenVAW2Q9Z17,Gate C-1 (DU_4_GC_C61),2019-03-08,11:00am,Participating in a Duke class,NaN,NaN,Nicki Cagle,Class,46,Cloudy,Yes,NaN,Yes,No,NaN,NaN,Red-backed Salamander (Plethodon cinereus) - L...,W-1,3.0,NaN,NaN,NaN,NaN,NaN,NaN,F_1gj2qWjEgZk84vQ,image/jpeg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
output_path = '/Users/harsshgolechha/Desktop/Research/test.csv'
S1_2019.to_csv(output_path, index=False)