In [26]:
import pandas as pd

In [32]:
S2_2018 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2018 Fall'))
S1_2019 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2019 S1'))
S2_2019 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2019 S2'))
S1_2020 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2022 S1'))
S1_2021 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2021(only NSOE courses data)'))
S1_2022 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2022 S1'))
S2_2022 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2022 S2'))
S1_2023 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2023 S1'))
S2_2023 = (pd.read_excel('/Users/harsshgolechha/Desktop/Research/HerpTransData_MASTER.xlsx','2023 S2'))

S2_2019.head()

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"Observation of Species\n\nCover ID should be coded ""Transect Short Code_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).13",Upload a ZIP file of all of your photos: - Id,Upload a ZIP file of all of your photos: - Name,Upload a ZIP file of all of your photos: - Size,Upload a ZIP file of all of your photos: - Type,"Comments\n\nPlease list any important comments about your findings, your photos, the status of the cover boards on the transect, if you were unable to monitor certain cover boards, or other important information we should know.",Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Id,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Name,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Size,Data Sheet Upload\n\nLast Step! Please upload a photo of your completed field data sheet. (PDF or JPG) - Type
0,2019-07-15 13:25:48,2019-07-15 13:35:56,IP Address,149.168.27.6,100,607,True,2019-07-15 13:35:57,R_2YhxoY95M9HosPk,NaN,...,NaN,NaN,NaN,NaN,NaN,Most cover boards were dry underneath.,F_2E5INTjIj0Nn2au,07-12-2019_22.pdf,393675.0,application/pdf
1,2019-07-13 17:44:59,2019-07-13 17:54:56,IP Address,107.15.96.222,100,596,True,2019-07-13 17:54:59,R_2SIENdUBde71Igu,NaN,...,NaN,F_DIGnIuC8lVziuBP,2019.07.13_48-1.zip,512616.0,application/zip,This is the same cover we saw American Toad in...,F_2VjOhodgvhLeW6K,DataSheet-48-1-190713.pdf,50301.0,application/pdf
2,2019-07-13 18:00:31,2019-07-13 18:11:06,IP Address,107.15.96.222,100,635,True,2019-07-13 18:11:11,R_QoduTBcQz21I7cJ,NaN,...,NaN,F_1i53arrET85qyeI,2019.07.13_48-2.zip,1502035.0,application/zip,T4 is splitting along the corrugations. Will n...,F_3MLrPjmZbNMF0tv,DataSheet-48-2-190713.pdf,50442.0,application/pdf
3,2019-07-14 07:04:10,2019-07-14 07:08:37,IP Address,174.109.101.4,100,266,True,2019-07-14 07:08:39,R_DwO6zKlJEK47Xnr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,F_1LFEfTV6NITZ65c,G4_sheet.jpg,1071125.0,image/jpeg
4,2019-07-27 10:05:00,2019-07-27 10:14:19,IP Address,162.198.201.245,100,559,True,2019-07-27 10:14:21,R_31TNaFzoQQrisix,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,F_1rkQZyMbwrcM4hV,IMG_1113.jpg,2322081.0,image/jpeg

In [28]:
#is this even needed?
""""S2_2018['Session']='2018_S2'
S1_2019['Session']='2019_S1'
S2_2019['Session']='2019_S2'
S1_2020['Session']='2020_S1'
S1_2021['Session']='2021_S1'
S1_2022['Session']='2022_S1'
S2_2022['Session']='2022_S2'
S1_2023['Session']='2023_S1'
S2_2023['Session']='2023_S2'"""

'"S2_2018[\'Session\']=\'2018_S2\'\nS1_2019[\'Session\']=\'2019_S1\'\nS2_2019[\'Session\']=\'2019_S2\'\nS1_2020[\'Session\']=\'2020_S1\'\nS1_2021[\'Session\']=\'2021_S1\'\nS1_2022[\'Session\']=\'2022_S1\'\nS2_2022[\'Session\']=\'2022_S2\'\nS1_2023[\'Session\']=\'2023_S1\'\nS2_2023[\'Session\']=\'2023_S2\''

In [29]:
### OBSOLETE DATA REMOVER FUNCTION

In [33]:
def obsolete_remover(data):
    data = data.drop('Start Date', axis=1)
    data = data.drop('End Date', axis=1)
    data = data.drop('Response Type', axis=1)
    data = data.drop('IP Address', axis=1)
    data = data.drop('Progress', axis=1)
    data = data.drop('Duration (in seconds)', axis=1)
    data = data.drop('Finished', axis=1)
    data = data.drop('Recorded Date', axis=1)
    data = data.drop('Location Latitude', axis=1)
    data = data.drop('Location Longitude', axis=1)
    data = data.drop('User Language', axis=1)
    """data = data.drop('', axis=1)
    data = data.drop('', axis=1)
    data = data.drop('', axis=1)
    data = data.drop('', axis=1)"""
    #data = data.drop(data.columns[[0,1,2,3,4,5,7,9,10,11,12,18]], axis=1)
    data = data.drop('Upload Your Photos - Id', axis=1)
    data = data.drop('Upload Your Photos - Size', axis=1)
    data = data.drop('Upload Your Photos - Type', axis=1)
    data = data.drop('Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT Ã¢â‚¬â€œ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: "2022.04.27_48-2_Datasheet.pdf" - Id', axis=1)
    data = data.drop('Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT Ã¢â‚¬â€œ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: "2022.04.27_48-2_Datasheet.pdf" - Size', axis=1)
    data = data.drop('Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT Ã¢â‚¬â€œ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: "2022.04.27_48-2_Datasheet.pdf" - Type', axis=1)
    data = data.dropna(axis=1,how='all')
    data = data.dropna(axis=0,how='all')
    return data

In [34]:
S1_2023 = obsolete_remover(S1_2023)

In [35]:
S1_2023.head()

,Response ID,Distribution Channel,Transect ID,Survey Date (mm/dd/yyyy),Survey Start Time\n\nRound to the closest hour.,Are you a Community Scientist or are you participating in a Duke class?,What team was scheduled for this transect?,Email Address,"Observer Names\n\nPlease include all Observers' full names, including First and Last names. - Recorder (you)","Observer Names\n\nPlease include all Observers' full names, including First and Last names. - Other Observer(s)",...,"Observation of Species\nCover ID should be coded ""Short Transect ID_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.11","Observation of Species\nCover ID should be coded ""Short Transect ID_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).11",Species/Occurrence 15,"Observation of Species\nCover ID should be coded ""Short Transect ID_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Cover ID.12","Observation of Species\nCover ID should be coded ""Short Transect ID_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Total.12","Observation of Species\nCover ID should be coded ""Short Transect ID_Cover ID"" (ex. 4_W2, 22_T3, 48-1_W9) - This Occurrence - Photo (y/n).12",Upload Your Photos - Name,"Data Sheet Upload\n\nLast Step! Please upload a scan or photo of your completed field data sheet whether you saw herps or not. (PDF or JPG please).\n\n\n\nIMPORTANT Ã¢â‚¬â€œ Please use the following naming convention to name the jpeg or pdf file of your datasheet: YYYY.MM.DD_transectID_Datasheet. For example: ""2022.04.27_48-2_Datasheet.pdf"" - Name","Comments/Issues\n\nPlease list any important comments about your data (observations, photos, or other important information we should know). \n\n\n\nIf you are a Community Scientist volunteer and have ""Damage to report"" or other transect conditions to report, please use the Transect Maintenance tab in the @Data channel in MS Teams. If you are a student/staff/researcher, please put it here.",Administrative Comments
0,R_1IrWBkt8ERCUndV,anonymous,Gate C-2 (DU_GC_C62),2023-01-27,14:00:00,Participating in a Duke Class (Grunwald),NaN,ron.grunwald@duke.edu,Ron Grunwald,"Angela Addae, Nia Williams, Emi Hegarty",...,NaN,NaN,NaN,NaN,NaN,NaN,2023.01.27_C-2_Photos.docx,2023.01.27_C-2_Data Sheet.pdf,NaN,Photos were not provided for every Red-Backed ...
1,R_2wTY0cgxaBqr19U,anonymous,Gate C-1 (DU_4_GC_C61),2023-01-27,14:00:00,Participating in a Duke Class (Grunwald),NaN,ron.grunwald@duke.edu,Maggie Heraty (on behalf of Ron Grunwald),"Bio348LS class (aggregate) - Angela Addae, Dan...",...,NaN,NaN,NaN,NaN,NaN,NaN,2023.01.27_C-1.docx,2023.01.27_C-1_Data sheet .pdf,ALL salamanders observed during this transect ...,NaN
2,R_23VuhDXGolsNvRo,anonymous,Gate 8 (DU_5_G8_C62),2023-02-16,17:00:00,Duke Forest Staff,NaN,NaN,Maggie Heraty,2023 Herp Program Make-up Training: Susan Prat...,...,NaN,NaN,NaN,NaN,NaN,NaN,2023.02.16_8_Photos.docx,2023.02.16_8_Datasheet.pdf,"At coverboard 8_T2, 20% of the ground surface ...",Field mouse observed at 8_T1.
3,R_ZLhhpkGHUkVwmU9,anonymous,Gate C-1 (DU_4_GC_C61),2023-02-18,13:00:00,Duke Forest Staff,NaN,NaN,Maggie Heraty,Field Trip for the Duke Health and Environment...,...,NaN,NaN,NaN,NaN,NaN,NaN,2023.02.18_C-1_Photos.docx,2023.02.18_C-1_Datasheet.JPG,This data was collected by undergraduate mento...,NaN
4,R_Y50h9t88mvyl7Cp,anonymous,Gate C-2 (DU_GC_C62),2023-02-18,13:00:00,Duke Forest Staff,NaN,NaN,Maggie Heraty,Field Trip for the Duke Health and Environment...,...,NaN,NaN,NaN,NaN,NaN,NaN,2023.02.18_C-2_Photos.docx,2023.02.18_C-2_Datasheet.JPG,This data was collected by undergraduate mento...,NaN

In [50]:
species_cols = [col for col in S1_2023.columns if 'Species/Occurrence ' in col]
sublist=species_cols
cover_id=S1_2023.iloc[:,S1_2023.columns.get_indexer(sublist)+1]
occurrence_total=S1_2023.iloc[:,S1_2023.columns.get_indexer(sublist)+2]
melt_species=pd.melt(S1_2023, id_vars=['Response ID','Survey Date (mm/dd/yyyy)','Survey Start Time\n\nRound to the closest hour.','Are you a Community Scientist or are you participating in a Duke class?','Transect ID','Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Ã‚Â°F" or "degrees".', 'Sky Condition / Precipitation Status'], value_vars= species_cols, var_name='Species_Occurrence',value_name='Species').sort_values('Response ID')
# make separate occurrence column
melt_species[['Species_OccurrenceCol', 'OccurrenceNum']] = melt_species['Species_Occurrence'].str.split(' ', expand=True)

In [52]:
species_cols = [col for col in S1_2023.columns if 'Species/Occurrence ' in col]
coverid_cols = [col for col in S1_2023.columns if 'Occurrence - Cover ID' in col]
total_cols = [col for col in S1_2023.columns if 'Occurrence - Total' in col]
melt_coverids=pd.melt(S1_2023, id_vars=['Response ID'], value_vars= coverid_cols,\
    var_name='Cover_ID', value_name='Transect_Cover').sort_values('Response ID')

In [53]:
species_cols = [col for col in S1_2023.columns if 'Species/Occurrence ' in col]
coverid_cols = [col for col in S1_2023.columns if 'Occurrence - Cover ID' in col]
total_cols = [col for col in S1_2023.columns if 'Occurrence - Total' in col]
melt_totals=pd.melt(S1_2023, id_vars=['Response ID'], value_vars= total_cols,var_name='Totals', value_name='Species_Totals').sort_values('Response ID')

In [55]:
usable_S1_2023 = pd.concat([melt_species,melt_coverids,melt_totals], axis="columns").drop_duplicates()
usable_S1_2023=usable_S1_2023[['Response ID','Survey Date (mm/dd/yyyy)','Survey Start Time\n\nRound to the closest hour.','Are you a Community Scientist or are you participating in a Duke class?','Transect ID','Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include "Ã‚Â°F" or "degrees".', 'Sky Condition / Precipitation Status','Species','OccurrenceNum','Transect_Cover','Species_Totals']]

In [56]:
usable_S1_2023.head()

,Response ID,Response ID,Response ID,Survey Date (mm/dd/yyyy),Survey Start Time\n\nRound to the closest hour.,Are you a Community Scientist or are you participating in a Duke class?,Transect ID,"Temperature, in degrees Fahrenheit.\n\n\n\n**Simply write the number, i.e. 55 or 78. No need to include ""Ã‚Â°F"" or ""degrees"".",Sky Condition / Precipitation Status,Species,OccurrenceNum,Transect_Cover,Species_Totals
1194,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,2023-02-19,10:00:00,Duke Forest Staff,Gate C-1 (DU_4_GC_C61),47.0,Sunny,Red-backed Salamander (Plethodon cinereus) - R...,10,C-1_W6,2
535,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,2023-02-19,10:00:00,Duke Forest Staff,Gate C-1 (DU_4_GC_C61),47.0,Sunny,NaN,5,NaN,NaN
1855,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,2023-02-19,10:00:00,Duke Forest Staff,Gate C-1 (DU_4_GC_C61),47.0,Sunny,NaN,15,NaN,NaN
1854,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,2023-02-19,10:00:00,Duke Forest Staff,Gate C-1 (DU_4_GC_C61),47.0,Sunny,Black Ants,15,C-1_T2,0.3
1723,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,R_10OaVqcM2ppFLsV,2023-02-19,10:00:00,Duke Forest Staff,Gate C-1 (DU_4_GC_C61),47.0,Sunny,NaN,14,NaN,NaN